from collections.abc import Mapping

from awsglue.context import GlueContext

class Job:
    def __init__(self, glue_context: GlueContext) -> None: ...
    def init(self, job_name: str, args: Mapping[str, str]) -> None: ...
    def commit(self) -> None: ...
